// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykxgdznqdoyaytbsfhpk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlreGdkem5xZG95YXl0YnNmaHBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwODEzMTUsImV4cCI6MjA2MTY1NzMxNX0.W_0wABGIZ918AixQLPPYUCUns24NDpIPLf4OaL8xYfs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);